# Завдання №1 "Створення та інспектування np-массивів"


## Завдання №1.1


In [1]:
import numpy as np

arr1_1 = np.array([[1.2, 2.3, 3.4, 4.5],
                   [5.6, 6.7, 7.8, 8.9],
                   [9.0, 10.1, 11.2, 12.3]])

np.info(arr1_1)

class:  ndarray
shape:  (3, 4)
strides:  (32, 8)
itemsize:  8
aligned:  True
contiguous:  True
fortran:  False
data pointer: 0x27762dedbc0
byteorder:  little
byteswap:  False
type: float64


In [2]:
import numpy as np

arr1_1 = np.array([[1.2, 2.3, 3.4, 4.5],
                   [5.6, 6.7, 7.8, 8.9],
                   [9.0, 10.1, 11.2, 12.3]])
print(arr1_1)

[[ 1.2  2.3  3.4  4.5]
 [ 5.6  6.7  7.8  8.9]
 [ 9.  10.1 11.2 12.3]]


## Завдання №1.2


In [3]:
arr1_2 = np.array(['ousmane', 'robert', 'ronald', 'marc', 'jules'])

print(arr1_2)

['ousmane' 'robert' 'ronald' 'marc' 'jules']


## Завдання №1.3


In [4]:
arr1_3 = np.ones((3, 4), dtype=float)

print(arr1_3)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


# Завдання №2 "Перетворення форми та типу массивів"


## Завдання №2.1


In [5]:
arr2_1 = np.zeros((3, 1, 3), dtype=bool)

print(arr2_1)

[[[False False False]]

 [[False False False]]

 [[False False False]]]


## Завдання №2.2


In [6]:
arr2_1 = np.zeros((3, 1, 3), dtype=bool)
arr2_2 = arr2_1.reshape(3, 3).astype(int)

print(arr2_2)

[[0 0 0]
 [0 0 0]
 [0 0 0]]


## Завдання №2.3


In [7]:
arr2_3 = np.arange(10, 21, 2).reshape(3, 2)

print(arr2_3)

[[10 12]
 [14 16]
 [18 20]]


# Завдання №3 "Доступ до елементів масива"


## Завдання №3.1


In [8]:
average, vidh = 55, 15
arr3_1 = np.random.normal(average, vidh, size=(4, 5))
print(arr3_1)

[[49.6651215  55.49182672 63.56547743 50.44812595 60.2464214 ]
 [61.66529792 52.42656319 70.18838934 72.26553991 62.7458433 ]
 [30.86165806 40.10688629 89.26584253 43.35970375 75.55107232]
 [84.00334434 42.13316293 42.78716381 53.80069406 66.43450453]]


## Завдання №3.2


In [9]:
el3_2 = arr3_1[1, 2]
print(el3_2)

70.18838933566222


## Завдання №3.3


In [10]:
vect3_3 = arr3_1[1]
print(vect3_3)

[61.66529792 52.42656319 70.18838934 72.26553991 62.7458433 ]


## Завдання №3.4


In [11]:

vect3_4 = arr3_1[:, 2]
print(vect3_4)

[63.56547743 70.18838934 89.26584253 42.78716381]


## Завдання №3.5


In [12]:
mat3_5 = arr3_1[1:3, 1:3]
print(mat3_5)

[[52.42656319 70.18838934]
 [40.10688629 89.26584253]]


# Завдання №4 "Матричні компоненти масива"


## Завдання №4.1


In [13]:
mat4_1 = np.random.randint(100, 201, size=(6, 6))
print(mat4_1)


[[187 194 184 170 103 191]
 [108 200 154 138 162 175]
 [150 144 114 179 150 189]
 [107 102 124 194 188 175]
 [125 112 148 148 166 114]
 [177 190 193 162 197 133]]


## Завдання №4.2


In [14]:
diag4_2 = [mat4_1[i][i] for i in range(len(mat4_1))]
print(diag4_2)

[187, 200, 114, 194, 166, 133]


## Завдання №4.3


In [15]:
trans4_3 = np.transpose(mat4_1)
print(trans4_3)

[[187 108 150 107 125 177]
 [194 200 144 102 112 190]
 [184 154 114 124 148 193]
 [170 138 179 194 148 162]
 [103 162 150 188 166 197]
 [191 175 189 175 114 133]]


## Завдання №4.4


In [16]:
inv4_4 = np.linalg.inv(mat4_1)
print(inv4_4)

[[-0.01027041  0.0044029   0.03799283 -0.05217389  0.06929976 -0.03578382]
 [ 0.00990624 -0.01521376 -0.03335561  0.06125039 -0.11567187  0.07174662]
 [ 0.00447406  0.0116701  -0.00303459 -0.02407034  0.05915494 -0.03650098]
 [ 0.02796137 -0.04494358 -0.07186854  0.1298413  -0.19896617  0.12080883]
 [-0.01811821  0.01463069  0.02702858 -0.04010993  0.06346962 -0.03326688]
 [-0.01419754  0.03201191  0.04899686 -0.08187861  0.13551652 -0.09226231]]


# Завдання №5 "Операції над масивами"


## Завдання №5.1


In [17]:
mat5_1 = np.random.randint(1, 10, size=(3,4))
print("Матриця:\n", mat5_1)

Матриця:
 [[5 8 9 2]
 [8 3 4 2]
 [6 8 4 3]]


In [18]:
sum_mat5_1 = np.sum(mat5_1, axis=1)
print("Суми елементів рядків:\n", sum_mat5_1)


Суми елементів рядків:
 [24 17 21]


## Завдання №5.2


In [19]:
min_mat5_1 = np.min(sum_mat5_1)
print(min_mat5_1)

17


## Завдання №5.3


In [20]:
mat5_3 = mat5_1 + 100
print(mat5_3)

[[105 108 109 102]
 [108 103 104 102]
 [106 108 104 103]]


## Завдання №5.4


In [21]:
mat5_4 = np.dot(mat5_1.T, np.diag(mat5_3))
print(mat5_4)

[1973 1981 1773  728]


## Завдання №5.5


In [22]:
mat5_5 = np.hstack((mat5_3.T, mat5_4.reshape(-1, 1)))
print(mat5_5)


[[ 105  108  106 1973]
 [ 108  103  108 1981]
 [ 109  104  104 1773]
 [ 102  102  103  728]]


In [23]:
rank = np.linalg.matrix_rank(mat5_5)
print("Ранг матриці: ", rank)

Ранг матриці:  4
